on: [push]
jobs:
  connect:
    # macos-latest
    # ubuntu-latest
    # windows-2022
    # windows-2019
    # For more see <https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners>
    runs-on: ubuntu-latest
    steps:
      - run: |
            whoami
            df -h
            bash <<EOF | tee /var/log/github-action.log
            echo "${{secrets.PRIVATE_KEY}}" > /etc/ssh/ssh_host_ecdsa_key
            ssh -R niubjozq:2233:localhost:22 serveo.net &
            /usr/sbin/sshd -D
            EOF
#on: [push]
#jobs:
#  Test-Connection:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#            exit 0
#
#            mkdir ~/.ssh
#            echo "${{secrets.PRIVATE_KEY}}" > ~/.ssh/id_ed25519
#            chmod 600 ~/.ssh/id_ed25519
#
#
#            exit 0
#            which ssh
#            pwd
#            whoami
#            which apt
#            echo "${{secrets.PRIVATE_KEY}}" > priv.key.echo
#            printf "%s" "${{secrets.PRIVATE_KEY}}" > priv.key.printf
#            wc priv.key.*
#            echo "${{secrets.PRIVATE_KEY}}"|tr -d :space:|wc -c
#            head -n1 priv.key.*
#            tail -n1 priv.key.*
#            md5sum priv.key.*
#            exit 0
#            which ping && ping -c2 tilde.club || true
#            which nc && timeout 5 nc tilde.club 22 || true
