on: [push]
jobs:
  Test-Connection:
    runs-on: ubuntu-latest
    steps:
      - run: |
            which ssh
            pwd
            whoami
            which apt
            echo "${{secrets.PRIVATE_KEY}}" > priv.key.echo
            printf "%s" "${{secrets.PRIVATE_KEY}}" > priv.key.printf
            wc priv.key.*
            echo "${{secrets.PRIVATE_KEY}}"|tr -d :space:|wc -c
            head -n1 priv.key.*
            tail -n1 priv.key.*
            md5sum priv.key.*
            exit 0
            which ping && ping -c2 tilde.club || true
            which nc && timeout 5 nc tilde.club 22 || true
