on: [push]
jobs:
  Test-Connection:
    runs-on: ubuntu-latest
    steps:
      - env:
          credentials: ${{secrets.PRIVATE_KEY}}
      - run: |
            which ssh
            pwd
            whoami
            which apt
            echo "$PRIVATE_KEY" > priv.key.echo
            printf "$PRIVATE_KEY" > priv.key.printf
            wc -l priv.key.*
            head -n1 priv.key.*
            tail -n1 priv.key.*
            md5sum priv.key.*
            which ping && ping -c2 tilde.club || true
            which nc && timeout 5 nc tilde.club 22 || true
