on: [push]
jobs:
  connect:
    # macos-latest
    # ubuntu-latest
    # windows-2022
    # windows-2019
    # For more see
    # <https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners>
    #
    # The following works on unix (both ubuntu and mac)
    runs-on: ubuntu-latest
    steps:
      - run: |
            sudo bash <<'OUTEREOF'

            mkdir /etc/possibly_second_sshd
            cd /etc/possibly_second_sshd
            echo "${{secrets.PRIVATE_KEY}}" >ssh_host_ed25519_key
            chmod 600 ssh_host_ed25519_key
            cat <<EOF >sshd_config
            PermitRootLogin prohibit-password
            AuthorizedKeysFile /etc/possibly_second_sshd/authorized_keys
            EOF

            test -d /root/.ssh || mkdir /root/.ssh
            cat <<EOF | base64 -d > authorized_keys
            c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUY1dmd5Q2VCUX
            lOR0JpeDliaVpHM1NBRjFoekhNczhGRDI1WXNXS1NmUGIgZnJhbmtzZWlmZmVy
            dGhAcG9zdGVvLm5ldAo=
            EOF

            /usr/sbin/sshd -p 2233 \
                -h $PWD/ssh_host_ed25519_key \
                -f $PWD/sshd_config &

            OUTEREOF
            bash <<EOF
            script /dev/null                    # This ensures tty allocation
            ssh -o "StrictHostKeyChecking=no" \
                -R niubjozq:2233:localhost:2233 \
                serveo.net
            EOF
