on: [push]
jobs:
  Test-Connection:
    runs-on: ubuntu-latest
    steps:
      - with:
          credentials: ${{secrets.PRIVATE_KEY}}
        env:
          credentials: ${{secrets.PRIVATE_KEY}}
        run: |
            which ssh
            pwd
            whoami
            which apt
            echo $PRIVATE_KEY
            exit 0
            echo "$PRIVATE_KEY" > priv.key.echo
            printf "$PRIVATE_KEY" > priv.key.printf
            wc priv.key.*
            echo "$PRIVATE_KEY"|tr -d :space:|wc -c
            head -n1 priv.key.*
            tail -n1 priv.key.*
            md5sum priv.key.*
            which ping && ping -c2 tilde.club || true
            which nc && timeout 5 nc tilde.club 22 || true
